---
  - hosts: all
    become: true
    tasks:
    
    - name: Bu gorev,Ubuntu apache2 ve  yuklemesini gerceklestirir ve paket indexisini günceller.
      ansible.builtin.package:
        name: 
          - "{{ apache_sunucusu }}"
          - "{{ php_kutuphane }}"
        state: latest
        update_cache: yes
      
    
   