---
  - hosts: all
    become: true
    tasks:


# Bu görev sunucu güncellemeleri için hazırlanmıştır.
    - name: Bu gorev,Ubuntu apache2 ve  yuklemesini gerceklestirir ve paket indexisini günceller.
      ansible.builtin.package:
          upgrade: dist
          update_cache: yes
      when: ansible_distribution == "Ubuntu" 


# Bu görev Ubuntu için apache ve php kutuphanesi yüklemesi yapar

  - hosts: web_sunuculari
    become: true
    tasks:
      
      - name: Isletim sistemlerini tespit et.
        debug: var=ansible_os_family

      - name: Dosyalardan degiskenleri oku
        include_vars: "{{ lookup('first_found', params) }}"
        vars:
          params:
            files:
              - "vars/apache_{{ ansible_os_family }}.yaml"
              - "vars/apache_varsayilan.yaml"
      
      - name: Bu gorev,Ubuntu apache2 ve  yuklemesini gerceklestirir ve paket indexisini günceller.
        ansible.builtin.package:
          name: 
            - "{{ apache_sunucusu }}"
            - "{{ php_kutuphane }}"
          state: latest
          update_cache: yes
   